[INFO   ] Logger: Record log in C:\Users\DELL\.kivy\logs\kivy_21-11-29_1.txt
[INFO   ] deps: Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] deps: Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] deps: Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "C:\Users\DELL\anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
[INFO   ] Python: Interpreter at "C:\Users\DELL\anaconda3\python.exe"
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Text: Provider: sdl2
[INFO   ] Audio: Providers: audio_sdl2 (audio_ffpyplayer ignored)
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "C:\Users\DELL\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
[WARNING] stderr:     return _run_code(code, main_globals, None,
[WARNING] stderr:   File "C:\Users\DELL\anaconda3\lib\runpy.py", line 87, in _run_code
[WARNING] stderr:     exec(code, run_globals)
[WARNING] stderr:   File "invaders\__main__.py", line 24, in <module>
[WARNING] stderr:     from app import *
[WARNING] stderr:   File "invaders\app.py", line 15, in <module>
[WARNING] stderr:     from wave import *
[WARNING] stderr:   File "invaders\wave.py", line 105
[WARNING] stderr:     self._ship =
[WARNING] stderr:                ^
[WARNING] stderr: SyntaxError: invalid syntax
